language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - "pep8 --repeat besnappy"
  - "pyflakes besnappy"
  - "py.test --cov=besnappy besnappy"
after_success:
  - coveralls
